import { useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { useMappingReport } from '@/hooks/useAcademic';
import { useMapStudentAcademic } from '@/hooks/useStudents';
import { palette, spacing } from '@/theme';
import { AcademicHierarchyFields, type HierarchySelection } from './AcademicHierarchyFields';
import { Button } from '../primitives/Button';
import { Card } from '../primitives/Card';
import { Text } from '../primitives/Text';
const empty:HierarchySelection={schoolId:'',departmentId:'',programId:'',batchId:'',sectionId:''};
export function StudentMappingPanel(){const report=useMappingReport();const map=useMapStudentAcademic();const [selected,setSelected]=useState<string|null>(null);const [value,setValue]=useState(empty);const item=report.data?.items.find(x=>x.id===selected);return <View style={styles.block}><Text variant="titleLg" color={palette.onSurface}>Students needing mapping</Text><Text color={palette.onSurfaceVariant}>Legacy values are reference only. Choose the complete hierarchy explicitly.</Text>{item?<Card style={styles.editor}><Text variant="bodyLg">{item.name} · {item.rollNumber}</Text><Text color={palette.onSurfaceVariant}>Legacy: {item.legacy.department}, semester {item.legacy.semester}, section {item.legacy.section}</Text><AcademicHierarchyFields value={value} onChange={setValue}/><View style={styles.actions}><Button label="Cancel" variant="secondary" onPress={()=>{setSelected(null);setValue(empty)}}/><Button label="Save mapping" disabled={!value.sectionId} loading={map.isPending} onPress={()=>void map.mutateAsync({studentId:item.id,mapping:value,version:item.version}).then(()=>{setSelected(null);setValue(empty)})}/></View></Card>:null}<Card padded={false}>{report.data?.items.length?report.data.items.map(row=><View key={row.id} style={styles.row}><View style={styles.flex}><Text variant="bodyLg">{row.name}</Text><Text color={palette.onSurfaceVariant}>{row.studentId} · {row.legacy.department} / Sem {row.legacy.semester} / {row.legacy.section}</Text></View><Button label="Map" size="sm" variant="secondary" onPress={()=>{setSelected(row.id);setValue(empty)}}/></View>):<Text style={styles.empty} color={palette.onSurfaceVariant}>{report.isLoading?'Loading…':'Every student is mapped.'}</Text>}</Card></View>}
const styles=StyleSheet.create({block:{gap:spacing.sm},editor:{gap:spacing.md},row:{flexDirection:'row',alignItems:'center',gap:spacing.sm,padding:spacing.md,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:palette.outlineVariant},flex:{flex:1},actions:{flexDirection:'row',justifyContent:'flex-end',gap:spacing.sm},empty:{padding:spacing.md}});
